apiVersion: v1
kind: Service
metadata:
    name: mysql
    labels:
        app: mysql
spec:
    clusterIP: None
    ports:
    -   port: 3306
    selector:
        app: mysql

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mysql-node
spec:
  serviceName: mysql
  selector:
    matchLabels:
        app: mysql
  replicas: 1
  template:
    metadata:
        labels:
            app: mysql
    spec:
        containers:
        -   name: mysql-node
            image: mysql:5.7
            volumeMounts:
            -   mountPath: "/var/lib/mysql"
                name: mysql-data
            ports:
            -   containerPort: 3306
            resources:
                requests:
                    cpu: "500m"
                    memory: "500Mi"

  volumeClaimTemplates:
  - metadata:
        name: mysql-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi

        
